#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TenhouPointCalculatorBeta3.Resource", IsApplication=true)]

namespace TenhouPointCalculatorBeta3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ChangBang = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DIYIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int QianBang = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001e
			public const int btnAgare = 2131034142;
			
			// aapt resource value: 0x7f050022
			public const int btnBackSpace = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int btnForTest = 2131034148;
			
			// aapt resource value: 0x7f050004
			public const int btnLeftPlayer = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int btnMePlayer = 2131034121;
			
			// aapt resource value: 0x7f050019
			public const int btnNagare = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int btnNewGame = 2131034112;
			
			// aapt resource value: 0x7f05001a
			public const int btnNextGame = 2131034138;
			
			// aapt resource value: 0x7f050021
			public const int btnNum0 = 2131034145;
			
			// aapt resource value: 0x7f05001b
			public const int btnNum1 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int btnNum2 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int btnNum3 = 2131034141;
			
			// aapt resource value: 0x7f050016
			public const int btnNum4 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int btnNum5 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int btnNum6 = 2131034136;
			
			// aapt resource value: 0x7f050011
			public const int btnNum7 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int btnNum8 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int btnNum9 = 2131034131;
			
			// aapt resource value: 0x7f050020
			public const int btnNumDiv = 2131034144;
			
			// aapt resource value: 0x7f050001
			public const int btnOppositePlayer = 2131034113;
			
			// aapt resource value: 0x7f050015
			public const int btnPriGame = 2131034133;
			
			// aapt resource value: 0x7f050006
			public const int btnRightPlayer = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int btnSetting = 2131034128;
			
			// aapt resource value: 0x7f05001f
			public const int btnShowGameLog = 2131034143;
			
			// aapt resource value: 0x7f050014
			public const int btnSuddenlyNagare = 2131034132;
			
			// aapt resource value: 0x7f050023
			public const int checkBoxDoubleRon = 2131034147;
			
			// aapt resource value: 0x7f050003
			public const int checkBoxLeftPlayer = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int checkBoxMePlayer = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int checkBoxOppositePlayer = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int checkBoxRightPlayer = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int imgViewChangBang = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int imgViewQianBang = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int textViewChangBang = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int textViewControl = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int textViewQianBang = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int textViewSession = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int textViewShowInput = 2131034127;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
