#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TenhouPointCalculatorBeta3.Resource", IsApplication=true)]

namespace TenhouPointCalculatorBeta3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ChangBang = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int DIYIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Main = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int QianBang = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001f
			public const int btnAgare = 2131165215;
			
			// aapt resource value: 0x7f070023
			public const int btnBackSpace = 2131165219;
			
			// aapt resource value: 0x7f070026
			public const int btnCancelReach = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int btnForTest = 2131165221;
			
			// aapt resource value: 0x7f070003
			public const int btnHelp = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int btnLeftPlayer = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int btnMePlayer = 2131165194;
			
			// aapt resource value: 0x7f07001a
			public const int btnNagare = 2131165210;
			
			// aapt resource value: 0x7f070000
			public const int btnNewGame = 2131165184;
			
			// aapt resource value: 0x7f07001b
			public const int btnNextGame = 2131165211;
			
			// aapt resource value: 0x7f070022
			public const int btnNum0 = 2131165218;
			
			// aapt resource value: 0x7f07001c
			public const int btnNum1 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int btnNum2 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int btnNum3 = 2131165214;
			
			// aapt resource value: 0x7f070017
			public const int btnNum4 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int btnNum5 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int btnNum6 = 2131165209;
			
			// aapt resource value: 0x7f070012
			public const int btnNum7 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int btnNum8 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int btnNum9 = 2131165204;
			
			// aapt resource value: 0x7f070021
			public const int btnNumDiv = 2131165217;
			
			// aapt resource value: 0x7f070001
			public const int btnOppositePlayer = 2131165185;
			
			// aapt resource value: 0x7f070016
			public const int btnPriGame = 2131165206;
			
			// aapt resource value: 0x7f070007
			public const int btnRightPlayer = 2131165191;
			
			// aapt resource value: 0x7f070011
			public const int btnSetting = 2131165201;
			
			// aapt resource value: 0x7f070020
			public const int btnShowGameLog = 2131165216;
			
			// aapt resource value: 0x7f070015
			public const int btnSuddenlyNagare = 2131165205;
			
			// aapt resource value: 0x7f070024
			public const int checkBoxDoubleRon = 2131165220;
			
			// aapt resource value: 0x7f070004
			public const int checkBoxLeftPlayer = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int checkBoxMePlayer = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int checkBoxOppositePlayer = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int checkBoxRightPlayer = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int imgViewChangBang = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int imgViewQianBang = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int textViewChangBang = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int textViewControl = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int textViewQianBang = 2131165199;
			
			// aapt resource value: 0x7f070006
			public const int textViewSession = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int textViewShowInput = 2131165200;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int Help = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int TodoList = 2131034113;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int database = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int theme = 2130968577;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
